# Generated by Django 5.2.3 on 2025-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_contact_number_adminotp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminotp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminregistration',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='email',
        ),
        migrations.AddField(
            model_name='adminotp',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='adminregistration',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
