# Generated by Django 5.2.3 on 2025-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_update_mobile_number_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='reset_type',
            field=models.CharField(choices=[('mobile', 'Mobile Number'), ('email', 'Email')], default='mobile', max_length=10),
        ),
    ]
